#!/bin/bash


folder=$HOME/Pictures/wallpapers/anime/

extensions='.jpeg|.webp|.jpg|.png'

pic=$( ls $folder | shuf -n 1 )


# pics=$( ls $folder )
#
# pic_array=()
# for file in $pics; do
#     pic_array+=($file)
# done
#
# n=$(( $RANDOM % ${#pic_array[@]} ))
#
# pic=$folder${pic_array[n]}
#
# # functionality to add a picture to a file

echo $folder$pic >> $HOME/.wallpapers.txt

wal -qi $folder$pic 


# no_of_pics=$(cat -n pics.txt | tail -1 | cut -bd ' ' -f 1)
# echo $n

# some self notes

# Generating random numbers -->
# echo $Random /# Pretty simple...
# seeding a randomly generated number...
# RANDOM = 1 -> Now the random number generated by $RANDOM will always be the same number

# Generating random numbers through nanoseconds....
# RANDOM=$(date +%s%N | cut -b10-19) -> It is a much better random generator entropy as it is based on seconds and nanoseconds time.

# for numbers in a range...
# echo $(( $RANDOM % 113 + 1)) -> Generates a random number between 1 and 113
# echo $(( $RANDOM % 20 + 5)) -> Generates a random number between 5 and 25
# echo $(( $RANDOM % 400 + 100)) -> Generates a random number between 100 and 500

# You get the gist...

# could also be done in this manner...
# echo $[ $RANDOM % 117 + 1 ] -> for generating a random number between 1 and 117
# echo $[ $RANDOM % 114 + 17 ] -> for generating a random number between 17 and 131

# and so on and so forth

